### ISSUE TITLE
Need a way to skip OEM URI validation

### ISSUE THREAD

**Issue by snk20501** [DMTF/Redfish-URI-Validator#4] opened 2019-08-26 02:14 UTC
Hi,

Tool doesn't have a way to skip level2 OEM resources, so will show unexpected ERRORs for OEM resources.

For example, if we have following OEM resource and show under ServiceRoot, tool will show Warning in test report and this is expected because OEM schema not included in openapi.ymal.

`"Oem": {
        "ABC": {
            "@odata.type": "#ABC.v1_0_0.ABC",
            "ABC": {
                "@odata.id": "/redfish/v1/ABC"
            }
        }
    }`

But resources under "/redfish/v1/ABC" will be reported as ERROR in report, because can't find match URI pattern in openapi.ymal, like "/redfish/v1/ABC/LogServices".

Please help to check this problem. Thank you so much.

BR,
Caffrey

**Comment by jautor** [comment] 2019-08-29 20:23
Discussion 8/29 - Will investigate this but agree there should be an option (probably default to true) to skip OEM resources as they won't validate against the standard/published schema files.

**Comment by snk20501** [comment] 2019-09-02 05:06
Good to know. Thanks for the support.

**Comment by billdodd** [comment] 2019-09-02 23:29
I can't reproduce the error. If I run the tool on a service with Oem resources, I can see warnings for Oem elements, like this:

<img width="1210" alt="Screen Shot 2019-09-02 at 6 25 43 PM" src="https://user-images.githubusercontent.com/3341721/64135548-27126a80-cdaf-11e9-81d8-bad34871d2fd.png">

But I don't see any errors.

Can you post a screenshot of the exact error you get along with the JSON of the resource that references the Oem resource?

**Comment by snk20501** [comment] 2019-09-04 05:22
@billdodd I will provide reference data.

**Comment by mraineri** [comment] 2019-09-09 22:34
@billdodd have you started work on this? Depending on the data given by @snk20501, I may be addressing this as part of fixing #1

**Comment by billdodd** [comment] 2019-09-09 22:47
@mraineri - No, I haven't. I wasn't able to reproduce the error, so was waiting for more detail from the originator.

**Comment by mraineri** [comment] 2019-09-23 23:06
If the report shows "warning" for OEM resources not listed in the "paths" object of the specified OpenAPI document, is this okay?

My expectation is that vendors should provide their own updated OpenAPI document with OEM URIs so that clients could generate documentation and code for a particular implementation if needed.

**Comment by mraineri** [comment] 2019-09-23 23:13
@jautor I could go either way on this, but I like the idea of having fewer arguments for the tool and accepting warnings for these scenarios. I know you feel strongly about presentation of tool output, so I'll let you make the final decision ;)

**Comment by jautor** [comment] 2019-09-24 01:34
I think a warning is fine here, as long as the message mentions that this is due to OEM (extension) usage, as opposed to a "wrong" URI - which would be a failure.  I agree that additional utility options are not likely to help here. 

So there's two OEM warning cases:
 - OEM schema type not listed in OpenAPI document 
 - OEM usage of a standard or listed type (contained in OpenAPI document) but a URI not listed.

I haven't looked, but I assume through the traversal that the utility knows that it is following OEM section links?

**Comment by mraineri** [comment] 2019-09-24 02:18
Yeah, both will show up as a warning. The code I'm adding doesn't care about schema type and purely builds a property hierarchy from Service Root to the resource under test. If "Oem" is in that hierarchy, it will show a warning and state "OEM resource X was not found in the OpenAPI specification", where X is the URI being tested.

**Comment by mraineri** [comment] 2019-09-30 19:26
Closing; resolved with recent PR.

**Closed as completed by mraineri** 2019-09-30 19:26 UTC
Labels: enhancement, good first issue
